# -*- coding: utf-8 -*-
"""charts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vqMiOJbBcPljqv1Jr9TJxfEFaEccqAzT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============ Helpers ============

def _ensure_datetime(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure Date column is datetime."""
    if not pd.api.types.is_datetime64_any_dtype(df["Date"]):
        df = df.copy()
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
    return df


def _base_style():
    """Base visual style for all charts."""
    plt.rcParams.update({
        "figure.figsize": (9, 4.8),
        "axes.titlesize": 13,
        "axes.titleweight": "bold",
        "axes.labelsize": 11,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "axes.grid": True,
        "grid.alpha": 0.25,
    })


# ============ 1. Monthly Total Points (line + area) ============

def plot_monthly_total_points(df: pd.DataFrame):
    """
    Pretty monthly sustainability points chart.
    - Line + soft area
    - Value labels above each point
    """
    df = _ensure_datetime(df)
    _base_style()

    monthly = (
        df.groupby(pd.Grouper(key="Date", freq="M"))["Points"]
        .sum()
        .reset_index()
    )

    if monthly["Points"].sum() == 0:
        print("No points available for monthly trend.")
        return

    plt.figure()

    # Line
    plt.plot(monthly["Date"], monthly["Points"], marker="o", linewidth=2.5)

    # Soft fill
    plt.fill_between(monthly["Date"], monthly["Points"], alpha=0.15)

    # Labels
    ymax = monthly["Points"].max()
    offset = ymax * 0.04 if ymax > 0 else 1.0
    for x, y in zip(monthly["Date"], monthly["Points"]):
        plt.text(x, y + offset, f"{int(y)}", ha="center", va="bottom", fontsize=8)

    plt.title("Total Sustainability Points per Month")
    plt.xlabel("Month")
    plt.ylabel("Points")
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()


# ============ 2. Points by Category (pie) ============

def plot_points_by_category_pie(df: pd.DataFrame, min_slice_pct: float = 3.0):
    """
    Pie chart of total points by Category.
    - Groups tiny slices into 'Other' for readability.
    - Uses soft colors and bold percentages.
    """
    _base_style()

    cat = (
        df.groupby("Category")["Points"]
        .sum()
        .sort_values(ascending=False)
    )

    total = cat.sum()
    if total <= 0:
        print("No points to display for category breakdown.")
        return

    labels = []
    values = []
    other_total = 0.0

    for label, val in cat.items():
        pct = (val / total) * 100.0
        if pct < min_slice_pct:
            other_total += val
        else:
            labels.append(str(label))
            values.append(val)

    if other_total > 0:
        labels.append("Other")
        values.append(other_total)

    plt.figure(figsize=(7, 7))

    colors = plt.cm.Set3(np.linspace(0, 1, len(values)))

    wedges, texts, autotexts = plt.pie(
        values,
        labels=labels,
        autopct="%1.1f%%",
        startangle=140,
        pctdistance=0.8,
        labeldistance=1.05,
        colors=colors,
        wedgeprops={"edgecolor": "white", "linewidth": 1.5},
        textprops={"fontsize": 10},
    )

    for autotext in autotexts:
        autotext.set_fontweight("bold")

    plt.title("Points by Category", pad=20)
    plt.axis("equal")
    plt.tight_layout()
    plt.show()


# ============ 3. Debit vs Credit Points (pie) ============

def plot_debit_vs_credit_pie(df: pd.DataFrame):
    """
    Pie chart of DEBIT vs CREDIT sourced points.
    - Requires 'PointType' column.
    - Shows how much comes from green spending vs refunds/returns.
    """
    _base_style()

    if "PointType" not in df.columns:
        print("PointType column not found; cannot plot debit vs credit.")
        return

    agg = df.groupby("PointType")["Points"].sum()
    agg = agg[agg > 0]

    if agg.empty:
        print("No points available for debit vs credit breakdown.")
        return

    plt.figure(figsize=(6, 6))

    colors = plt.cm.Pastel1(np.linspace(0, 1, len(agg)))

    wedges, texts, autotexts = plt.pie(
        agg.values,
        labels=agg.index.astype(str),
        autopct="%1.1f%%",
        startangle=90,
        pctdistance=0.8,
        labeldistance=1.1,
        colors=colors,
        wedgeprops={"edgecolor": "white", "linewidth": 1.4},
        textprops={"fontsize": 10},
    )

    for autotext in autotexts:
        autotext.set_fontweight("bold")

    plt.title("Share of Points: Debit vs Credit", pad=18)
    plt.axis("equal")
    plt.tight_layout()
    plt.show()


# ============ 4. Optional: Simple router for LLM questions ============

def render_chart_for_question(df: pd.DataFrame, question: str):
    """
    Call this from your LLM layer.
    Chooses which chart to render based on keywords in the question.
    """
    q = question.lower()

    if any(k in q for k in ["trend", "monthly", "progress", "timeline"]):
        plot_monthly_total_points(df)
    elif any(k in q for k in ["category", "breakdown", "which area", "by type"]):
        plot_points_by_category_pie(df)
    elif any(k in q for k in ["debit vs credit", "refund", "return", "rebate", "bottle"]):
        plot_debit_vs_credit_pie(df)
    else:
        # default: category view
        plot_points_by_category_pie(df)

from sustainability_charts import (
    plot_monthly_total_points,
    plot_points_by_category_pie,
    plot_debit_vs_credit_pie,
    render_chart_for_question,
)

# df_points is your scored dataframe
plot_monthly_total_points(df_points)
plot_points_by_category_pie(df_points)
plot_debit_vs_credit_pie(df_points)

# or via LLM question:
# render_chart_for_question(df_points, "Show my sustainability trend")