# -*- coding: utf-8 -*-
"""sustainability scoring and redemption rules.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cW-qpxR16mroivpXIcfED51ApF7wbKOF
"""

# 1️⃣ GREEN POINTS FOR DEBITS (MONEY SPENT ON SUSTAINABLE CHOICES)

GREEN_DEBIT_RULES = {
    "PUBLIC_TRANSIT_MONTHLY_PASS": {
        "label": "Monthly bus pass or equivalent recurring public transit pass",
        # Directly matches your sample CSV
        "match_any": [
            "Monthly Bus Pass - Halifax Transit"
        ],
        # Strong reward: locked-in car-free commuting for the month
        "points_fixed": 50
    },

    "PUBLIC_TRANSIT_TOPUP": {
        "label": "Stored-value transit reloads (tap card, etc.)",
        "match_any": [
            "Transit Reload - Halifax Transit"
        ],
        # Reward proportional to usage, but capped
        "points_per_dollar": 0.5,        # 0.5 points per $1
        "max_points_per_month": 40
    },

    "THRIFT_REFURBISHED_PURCHASE": {
        "label": "Thrift store / second-hand / refurbished items",
        # These are matched after LLM/logic tags; you can also map real merchants here.
        "keywords_any": [
            "Thrift",
            "Thrift Store",
            "Refurb",
            "Refurbished",
            "Consignment",
            "Used Gear",
            "Used Book",
            "Marketplace (Used)"
        ],
        # Higher reward per dollar than normal shopping
        "points_per_dollar": 0.8,        # 0.8 pts per $1
        "max_points_per_month": 100
    },

    "SOLAR_PANEL_INVESTMENT": {
        "label": "Solar panel purchase, installation, or loan payments",
        "keywords_any": [
            "Solar Panel",
            "Solar Install",
            "Solar Loan",
            "PV System"
        ],
        # Big, long-term impact → generous score, but capped overall
        "points_per_dollar": 1.0,        # 1 pt per $1
        "max_points_total": 1000         # lifetime cap for one system
    },

    "ELECTRICITY_BILL": {
        "label": "Electricity bill vs baseline for home size (season-aware in your logic)",
        "match_any": [
            "Electricity Bill - Nova Scotia Power"
        ],

        # Example baselines (CAD/month). Adjust using local data or historic user average.
        "baseline_bill_cad": {
            "1BHK": 120,
            "2BHK": 160,
            "3BHK": 200
        },

        # Apply on MONTHLY total. ratio = actual_bill / baseline
        # First tier that matches wins.
        "tiers": [
            {
                "max_ratio_of_baseline": 1.00,   # <= baseline
                "points": 40
            },
            {
                "max_ratio_of_baseline": 1.10,   # <= 110% of baseline
                "points": 25
            }
        ],
        # If above highest tier: no points
        "points_if_above_threshold": 0
    },

    "WATER_BILL": {
        "label": "Water bill vs baseline for home size",
        "match_any": [
            "Water Bill - Halifax Water"
        ],

        # Example baselines (CAD/month)
        "baseline_bill_cad": {
            "1BHK": 45,
            "2BHK": 60,
            "3BHK": 75
        },

        "tiers": [
            {
                "max_ratio_of_baseline": 1.00,
                "points": 30
            },
            {
                "max_ratio_of_baseline": 1.10,
                "points": 15
            }
        ],
        "points_if_above_threshold": 0
    },

    "ACTIVE_COMMUTE": {
        "label": "Walking / cycling instead of car (from GPS / Google Fit)",
        # This uses external data; you award monthly summary points.
        "external_source": "fitness_tracker",
        "points_per_km": 2,              # e.g. 2 pts per km walked/biked instead of driven
        "max_points_per_month": 120
    }
}

# 2️⃣ GREEN POINTS FOR CREDITS (MONEY BACK FROM GREEN ACTIONS)

GREEN_CREDIT_RULES = {
    "BOTTLE_RETURN": {
        "label": "Refunds from returning bottles/containers",
        # Matches your CSV entries directly
        "match_any": [
            "Bottle Return Credit",
            "Bottle Deposit Refund",
            "Recycling Centre Refund - Halifax"
        ],
        # Strong incentive: turn every $ returned into a nice chunk of points
        "points_per_dollar": 10
    },

    "GREEN_REBATE": {
        "label": "Utility/government rebates for efficiency or solar",
        "keywords_any": [
            "Energy Rebate",
            "Solar Rebate",
            "Heat Pump Rebate",
            "Green Homes Rebate"
        ],
        # Bigger reward for structural improvements
        "points_per_dollar": 15
    },

    "RESALE_EARNINGS": {
        "label": "Money earned by selling used items instead of throwing them",
        "keywords_any": [
            "Facebook Marketplace Payout",
            "Kijiji",
            "Consignment Payout",
            "Thrift Sale Payout"
        ],
        # Reward circular economy behaviour
        "points_per_dollar": 6
    }
}

REDEMPTION_RULES = {
    # 1️⃣ TAX-STYLE BENEFITS (HYPOTHETICAL / POLICY-LAYER)
    "TAX": {
        "label": "Convert annual sustainability points into a small tax credit.",
        # Minimum engagement to qualify
        "min_points_for_any_credit": 2000,

        # Default flat conversion if you don't want tiers:
        # e.g. 120 pts = $1 credit → 12,000 pts = $100
        "default_conversion_points_per_cad": 120,

        # Hard cap so program cost is predictable
        "max_annual_tax_credit_cad": 150,

        # Optional tiered rates if you want to reward higher effort more efficiently
        "tiers": [
            {
                "min_points": 2000,
                "max_points": 4999,
                "conversion_points_per_cad": 150  # less generous
            },
            {
                "min_points": 5000,
                "max_points": 9999,
                "conversion_points_per_cad": 120
            },
            {
                "min_points": 10000,
                "max_points": None,  # open upper bound
                "conversion_points_per_cad": 100  # best rate
            }
        ],

        # Note: Your backend should:
        #  - Compute eligible_points (cap at max tier scenario)
        #  - Apply appropriate tier or default_conversion_points_per_cad
        #  - Enforce max_annual_tax_credit_cad
    },

    # 2️⃣ TRANSIT REWARDS (BUS PASSES, RIDES)
    "BUS_PASS": {
        "label": "Redeem points for public transit products.",
        # Example values roughly aligned with a ~$90 monthly pass.
        # You can read these as “this many points burns for this reward”.
        "rewards": {
            "MONTHLY_PASS_STANDARD": {
                "description": "1x standard adult monthly bus pass",
                "points_cost": 4000,
                "approx_value_cad": 90
            },
            "WEEKLY_PASS": {
                "description": "1x 7-day unlimited travel pass",
                "points_cost": 1500,
                "approx_value_cad": 25
            },
            "TEN_RIDE_BUNDLE": {
                "description": "10 single-ride tickets",
                "points_cost": 400,
                "approx_value_cad": 30
            }
        },
        # To avoid farming: only allow using points for transit in the
        # region where they were earned, and once per period if needed.
    },

    # 3️⃣ GREEN PURCHASE REWARDS (THRIFT, SOLAR, ETC.)
    "GREEN_PURCHASES": {
        "label": "Redeem points as vouchers/discounts at approved green merchants.",
        "rewards": {
            "THRIFT_25": {
                "description": "$25 voucher at participating thrift / reuse / refurbished stores",
                "points_cost": 2500,
                "value_cad": 25,
                "eligible_merchants_tags": [
                    "thrift_store", "second_hand", "refurbished", "reuse_centre"
                ]
            },
            "THRIFT_50": {
                "description": "$50 voucher for second-hand / refurbished purchases",
                "points_cost": 4500,
                "value_cad": 50
            },
            "GREEN_GROCER_25": {
                "description": "$25 voucher for local / organic / bulk-store groceries",
                "points_cost": 2500,
                "value_cad": 25,
                "eligible_merchants_tags": [
                    "local_produce", "bulk_food", "organic_store"
                ]
            },
            "SOLAR_EFFICIENCY_100": {
                "description": "$100 credit on solar panels / heat pumps / home efficiency upgrades",
                "points_cost": 8000,
                "value_cad": 100,
                "eligible_uses": [
                    "solar_panel", "heat_pump", "home_insulation",
                    "energy_star_appliance", "led_lighting_bulk"
                ]
            }
        }
    }
}

